import { Button, VerticalBox, TextEdit, ListView, LineEdit, AboutSlint } from "std-widgets.slint";

struct EmojiModel {
    name: string,
    code: string,
    image: image
}

export component EmojiPickerWindow inherits Window {
    always-on-top: true;
    width: 400px;
    height: 600px;
    title: "Emojis";
    icon: @image-url("../assets/ico-16.png");

    in property <[EmojiModel]> emojis;
    callback filter <=> filter-tb.edited;
    callback close-requested;
    callback emoji-selected(EmojiModel);

    FocusScope { 
        key-pressed(e) => {
            if e.text == Key.Escape {
                close-requested();
                accept;
            } else {
                reject;
            }
        }

        VerticalBox {
            if emojis.length > 0 : ListView {
                for emoji in emojis: Button {
                    text: emoji.name;
                    icon: emoji.image;
                    clicked => {
                        emoji-selected(emoji);
                    }
                }
            }
            if emojis.length == 0 : Text {
                text: "No emojis found";
            }
            
            filter-tb := LineEdit {
                text: "";
                placeholder-text: "Filter emojis";
                height: 30px;
            }
        }
    }
}