import { EmojiModel, EmojiGroupModel } from "emoji-model.slint";
import { EmojiGroupList } from "emoji-group.slint";
import { Button, VerticalBox, TextEdit, ListView, LineEdit, AboutSlint, ScrollView } from "std-widgets.slint";

export component EmojiPickerWindow inherits Window {
    always-on-top: true;
    width: 400px;
    height: 600px;
    title: "Emojis";
    icon: @image-url("../assets/ico-16.png");

    in property <[EmojiGroupModel]> emoji_groups;

    callback filter <=> filter-tb.edited;
    callback close-requested;
    callback emoji-selected(EmojiModel);

    public function on-open() {
        filter-tb.focus();
    }

    FocusScope { 
        key-pressed(e) => {
            if e.text == Key.Escape {
                close-requested();
                accept;
            } else {
                reject;
            }
        }

        VerticalBox {
            EmojiGroupList {
                groups: emoji_groups;
                emoji-selected(e) => {
                    emoji-selected(e);
                }
            }
            
            filter-tb := LineEdit {
                text: "";
                placeholder-text: "Filter emojis";
                height: 30px;
            }
        }
    }
}